### PR TITLE
refactor isc.Assets

### PR DESCRIPTION
**Pull request by howjmay**

### CODE REVIEW

**Review by jorgemmsilva — APPROVED** [review]

**Comment by howjmay** [comment]
Serialization hasn't passed

**Comment by howjmay** [comment]
@jorgemmsilva assets_test.go all passed, but other tests are not. Should we merge it?

**Comment by lmoe** [comment]
I'll need it in the vm, so I would vote for yes. :D 

@howjmay @jorgemmsilva

**Comment by jorgemmsilva** [comment]
ship it :rocket:

**Comment by howjmay** [comment]
merged

**Pull request merged**
